version: '2.4'
services:
  ocr-server:
    build: 
      context: .
      target: dev
    ports: 
      - "5004:5000"
    volumes:
      - ./src:/src/src
      - ./img:/img
      - ./numbers:/numbers
    environment:
      - PYTHONUNBUFFERED=1
    env_file: 
      - .minio.env
    depends_on: 
      minio:
        condition: service_healthy
  minio:
    image: minio/minio
    ports: 
      - 9000:9000
    env_file: 
      - .minio.env
    command: server /data
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/live || exit 1
      interval: 5s