version: '2.4'
services:
  ocr-server:
    build: 
      context: .
      target: dev
    ports: 
      - "5002:5000"
    volumes:
      - ./src:/src/src
      - ./img:/img
    environment:
      - PYTHONUNBUFFERED=1