version: '2.4'
services:
  ocr-server:
    build: 
      context: .
      target: dev
    ports: 
      - "5004:5000"
    volumes:
      - ./src:/src/src
      - ./img:/img
      - ./numbers:/numbers
    environment:
      - PYTHONUNBUFFERED=1
  minio:
    image: minio/minio
    ports: 
      - 9000:9000
    environment: 
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data